/////////////////////////////////////////////////////////////////////////////////
//*****************************************************************************//
//* Project      : CryptoHash                                                 *//
//* Latest Source: https://github.com/vampirsoft/CryptoHash                   *//
//* Unit Name    : CryptoHash.inc                                             *//
//* Author       : Сергей (LordVampir) Дворников                              *//
//* Copyright 2021 LordVampir (https://github.com/vampirsoft)                 *//
//* Licensed under MIT                                                        *//
//*****************************************************************************//
/////////////////////////////////////////////////////////////////////////////////

program CryptoHash;

{$INCLUDE CryptoHash.Tests.inc}

{$IFDEF CONSOLE_TESTRUNNER}
{$APPTYPE CONSOLE}
{$ENDIF ~ CONSOLE_TESTRUNNER}

uses
  DUnitTestRunner,
// core units
  {$IF NOT DEFINED(USE_JEDI_CORE_LIBRARY)}
  chHash.Core,
  {$ENDIF ~ NOT USE_JEDI_CORE_LIBRARY}
  chHash.Core.Bits,
// base units
  chHash,
  chHash.Impl,
// crc units
  chHash.CRC,
  chHash.CRC.Impl,
  chHash.CRC.CRC8Bits,
  chHash.CRC.CRC16Bits,
  chHash.CRC.CRC32Bits,
// crc-3 units
  chHash.CRC.CRC3,
  chHash.CRC.CRC3.Impl,
  chHash.CRC.CRC3.Reverse,
  chHash.CRC.CRC3.GSM,
  chHash.CRC.CRC3.ROHC,
  chHash.CRC.CRC3.GSM.Factory,
  chHash.CRC.CRC3.ROHC.Factory,
// crc-4 units
  chHash.CRC.CRC4,
  chHash.CRC.CRC4.Impl,
  chHash.CRC.CRC4.Reverse,
  chHash.CRC.CRC4.G704,
  chHash.CRC.CRC4.INTERLAKEN,
  chHash.CRC.CRC4.G704.Factory,
  chHash.CRC.CRC4.INTERLAKEN.Factory,
// crc-5 units
  chHash.CRC.CRC5,
  chHash.CRC.CRC5.Impl,
  chHash.CRC.CRC5.Reverse,
  chHash.CRC.CRC5.EPCC1G2,
  chHash.CRC.CRC5.G704,
  chHash.CRC.CRC5.USB,
  chHash.CRC.CRC5.EPCC1G2.Factory,
  chHash.CRC.CRC5.G704.Factory,
  chHash.CRC.CRC5.USB.Factory,
// crc-6 units
  chHash.CRC.CRC6,
  chHash.CRC.CRC6.Impl,
  chHash.CRC.CRC6.Reverse,
  chHash.CRC.CRC6.CDMA2000A,
  chHash.CRC.CRC6.CDMA2000B,
  chHash.CRC.CRC6.DARC,
  chHash.CRC.CRC6.G704,
  chHash.CRC.CRC6.GSM,
  chHash.CRC.CRC6.CDMA2000A.Factory,
  chHash.CRC.CRC6.CDMA2000B.Factory,
  chHash.CRC.CRC6.DARC.Factory,
  chHash.CRC.CRC6.G704.Factory,
  chHash.CRC.CRC6.GSM.Factory,
// crc-7 units
  chHash.CRC.CRC7,
  chHash.CRC.CRC7.Impl,
  chHash.CRC.CRC7.Reverse,
  chHash.CRC.CRC7.MMC,
  chHash.CRC.CRC7.ROHC,
  chHash.CRC.CRC7.UMTS,
  chHash.CRC.CRC7.MMC.Factory,
  chHash.CRC.CRC7.ROHC.Factory,
  chHash.CRC.CRC7.UMTS.Factory,
// crc-8 units
  chHash.CRC.CRC8,
  chHash.CRC.CRC8.Impl,
  chHash.CRC.CRC8.AUTOSAR,
  chHash.CRC.CRC8.BLUETOOTH,
  chHash.CRC.CRC8.CDMA2000,
  chHash.CRC.CRC8.DARC,
  chHash.CRC.CRC8.DVBS2,
  chHash.CRC.CRC8.GSMA,
  chHash.CRC.CRC8.GSMB,
  chHash.CRC.CRC8.I4321,
  chHash.CRC.CRC8.ICODE,
  chHash.CRC.CRC8.LTE,
  chHash.CRC.CRC8.MAXIMDOW,
  chHash.CRC.CRC8.MIFAREMAD,
  chHash.CRC.CRC8.NRSC5,
  chHash.CRC.CRC8.OPENSAFETY,
  chHash.CRC.CRC8.ROHC,
  chHash.CRC.CRC8.SAEJ1850,
  chHash.CRC.CRC8.SMBUS,
  chHash.CRC.CRC8.TECH3250,
  chHash.CRC.CRC8.WCDMA,
  chHash.CRC.CRC8.AUTOSAR.Factory,
  chHash.CRC.CRC8.BLUETOOTH.Factory,
  chHash.CRC.CRC8.CDMA2000.Factory,
  chHash.CRC.CRC8.DARC.Factory,
  chHash.CRC.CRC8.DVBS2.Factory,
  chHash.CRC.CRC8.GSMA.Factory,
  chHash.CRC.CRC8.GSMB.Factory,
  chHash.CRC.CRC8.I4321.Factory,
  chHash.CRC.CRC8.ICODE.Factory,
  chHash.CRC.CRC8.LTE.Factory,
  chHash.CRC.CRC8.MAXIMDOW.Factory,
  chHash.CRC.CRC8.MIFAREMAD.Factory,
  chHash.CRC.CRC8.NRSC5.Factory,
  chHash.CRC.CRC8.OPENSAFETY.Factory,
  chHash.CRC.CRC8.ROHC.Factory,
  chHash.CRC.CRC8.SAEJ1850.Factory,
  chHash.CRC.CRC8.SMBUS.Factory,
  chHash.CRC.CRC8.TECH3250.Factory,
  chHash.CRC.CRC8.WCDMA.Factory,
// crc-10 units
  chHash.CRC.CRC10,
  chHash.CRC.CRC10.Impl,
  chHash.CRC.CRC10.ATM,
  chHash.CRC.CRC10.CDMA2000,
  chHash.CRC.CRC10.GSM,
  chHash.CRC.CRC10.ATM.Factory,
  chHash.CRC.CRC10.CDMA2000.Factory,
  chHash.CRC.CRC10.GSM.Factory,
// crc-11 units
  chHash.CRC.CRC11,
  chHash.CRC.CRC11.Impl,
  chHash.CRC.CRC11.FLEXRAY,
  chHash.CRC.CRC11.UMTS,
  chHash.CRC.CRC11.FLEXRAY.Factory,
  chHash.CRC.CRC11.UMTS.Factory,
// crc-12 units
  chHash.CRC.CRC12,
  chHash.CRC.CRC12.Impl,
  chHash.CRC.CRC12.CDMA2000,
  chHash.CRC.CRC12.DECT,
  chHash.CRC.CRC12.GSM,
  chHash.CRC.CRC12.UMTS,
  chHash.CRC.CRC12.CDMA2000.Factory,
  chHash.CRC.CRC12.DECT.Factory,
  chHash.CRC.CRC12.GSM.Factory,
  chHash.CRC.CRC12.UMTS.Factory,
// crc-13 units
  chHash.CRC.CRC13,
  chHash.CRC.CRC13.Impl,
  chHash.CRC.CRC13.BBC,
  chHash.CRC.CRC13.BBC.Factory,
// crc-14 units
  chHash.CRC.CRC14,
  chHash.CRC.CRC14.Impl,
  chHash.CRC.CRC14.Reverse,
  chHash.CRC.CRC14.DARC,
  chHash.CRC.CRC14.GSM,
  chHash.CRC.CRC14.DARC.Factory,
  chHash.CRC.CRC14.GSM.Factory,
// crc-15 units
  chHash.CRC.CRC15,
  chHash.CRC.CRC15.Impl,
  chHash.CRC.CRC15.CAN,
  chHash.CRC.CRC15.MPT1327,
  chHash.CRC.CRC15.CAN.Factory,
  chHash.CRC.CRC15.MPT1327.Factory,
// crc-16 units
  chHash.CRC.CRC16,
  chHash.CRC.CRC16.Impl,
  chHash.CRC.CRC16.Reverse,
  chHash.CRC.CRC16.ARC,
  chHash.CRC.CRC16.CDMA2000,
  chHash.CRC.CRC16.CMS,
  chHash.CRC.CRC16.DDS110,
  chHash.CRC.CRC16.DECTR,
  chHash.CRC.CRC16.DECTX,
  chHash.CRC.CRC16.DNP,
  chHash.CRC.CRC16.EN13757,
  chHash.CRC.CRC16.GENIBUS,
  chHash.CRC.CRC16.GSM,
  chHash.CRC.CRC16.IBM3740,
  chHash.CRC.CRC16.IBMSDLC,
  chHash.CRC.CRC16.ISOIEC144433A,
  chHash.CRC.CRC16.KERMIT,
  chHash.CRC.CRC16.LJ1200,
  chHash.CRC.CRC16.MAXIMDOW,
  chHash.CRC.CRC16.MCRF4XX,
  chHash.CRC.CRC16.MODBUS,
  chHash.CRC.CRC16.NRSC5,
  chHash.CRC.CRC16.OPENSAFETYA,
  chHash.CRC.CRC16.OPENSAFETYB,
  chHash.CRC.CRC16.PROFIBUS,
  chHash.CRC.CRC16.RIELLO,
  chHash.CRC.CRC16.SPIFUJITSU,
  chHash.CRC.CRC16.T10DIF,
  chHash.CRC.CRC16.TELEDISK,
  chHash.CRC.CRC16.TMS37157,
  chHash.CRC.CRC16.UMTS,
  chHash.CRC.CRC16.USB,
  chHash.CRC.CRC16.XMODEM,
  chHash.CRC.CRC16.ARC.Factory,
  chHash.CRC.CRC16.CDMA2000.Factory,
  chHash.CRC.CRC16.CMS.Factory,
  chHash.CRC.CRC16.DDS110.Factory,
  chHash.CRC.CRC16.DECTR.Factory,
  chHash.CRC.CRC16.DECTX.Factory,
  chHash.CRC.CRC16.DNP.Factory,
  chHash.CRC.CRC16.EN13757.Factory,
  chHash.CRC.CRC16.GENIBUS.Factory,
  chHash.CRC.CRC16.GSM.Factory,
  chHash.CRC.CRC16.IBM3740.Factory,
  chHash.CRC.CRC16.IBMSDLC.Factory,
  chHash.CRC.CRC16.ISOIEC144433A.Factory,
  chHash.CRC.CRC16.KERMIT.Factory,
  chHash.CRC.CRC16.LJ1200.Factory,
  chHash.CRC.CRC16.MAXIMDOW.Factory,
  chHash.CRC.CRC16.MCRF4XX.Factory,
  chHash.CRC.CRC16.MODBUS.Factory,
  chHash.CRC.CRC16.NRSC5.Factory,
  chHash.CRC.CRC16.OPENSAFETYA.Factory,
  chHash.CRC.CRC16.OPENSAFETYB.Factory,
  chHash.CRC.CRC16.PROFIBUS.Factory,
  chHash.CRC.CRC16.RIELLO.Factory,
  chHash.CRC.CRC16.SPIFUJITSU.Factory,
  chHash.CRC.CRC16.T10DIF.Factory,
  chHash.CRC.CRC16.TELEDISK.Factory,
  chHash.CRC.CRC16.TMS37157.Factory,
  chHash.CRC.CRC16.UMTS.Factory,
  chHash.CRC.CRC16.USB.Factory,
  chHash.CRC.CRC16.XMODEM.Factory,
// crc-17 units
  chHash.CRC.CRC17,
  chHash.CRC.CRC17.Impl,
  chHash.CRC.CRC17.CANFD,
  chHash.CRC.CRC17.CANFD.Factory,
// crc-21 units
  chHash.CRC.CRC21,
  chHash.CRC.CRC21.Impl,
  chHash.CRC.CRC21.CANFD,
  chHash.CRC.CRC21.CANFD.Factory,
// crc-31 units
  chHash.CRC.CRC31,
  chHash.CRC.CRC31.Impl,
  chHash.CRC.CRC31.PHILIPS,
  chHash.CRC.CRC31.PHILIPS.Factory,
// crc-32 units
  chHash.CRC.CRC32,
  chHash.CRC.CRC32.Impl,
  chHash.CRC.CRC32.PKZIP,
  chHash.CRC.CRC32.BZIP2,
  chHash.CRC.CRC32.ISCSI,
  chHash.CRC.CRC32.BASE91D,
  chHash.CRC.CRC32.MPEG2,
  chHash.CRC.CRC32.CKSUM,
  chHash.CRC.CRC32.AIXM,
  chHash.CRC.CRC32.JAMCRC,
  chHash.CRC.CRC32.XFER,
  chHash.CRC.CRC32.AUTOSAR,
  chHash.CRC.CRC32.CDROMEDC,
  chHash.CRC.CRC32.PKZIP.Factory,
  chHash.CRC.CRC32.BZIP2.Factory,
  chHash.CRC.CRC32.ISCSI.Factory,
  chHash.CRC.CRC32.BASE91D.Factory,
  chHash.CRC.CRC32.MPEG2.Factory,
  chHash.CRC.CRC32.CKSUM.Factory,
  chHash.CRC.CRC32.AIXM.Factory,
  chHash.CRC.CRC32.JAMCRC.Factory,
  chHash.CRC.CRC32.XFER.Factory,
  chHash.CRC.CRC32.AUTOSAR.Factory,
  chHash.CRC.CRC32.CDROMEDC.Factory,
// utils units
  chHash.Utils,
// tests units
  chHash.Core.Bits.Tests,
  chHash.Core.Byte.Tests,
  chHash.Core.ShortInt.Tests,
  chHash.Core.Word.Tests,
  chHash.Core.SmallInt.Tests,
  chHash.Core.Cardinal.Tests,
  chHash.Core.Integer.Tests,
  chHash.Core.UInt64.Tests,
  chHash.Core.Int64.Tests,
  chHash.Core.NativeUInt.Tests,
  chHash.Core.NativeInt.Tests,
  chHash.Core.Pointer.Tests,
  chHash.Tests,
  chHash.CRC.Tests,
  chHash.CRC.CRC16Bits.Tests,
  chHash.CRC.CRC32Bits.Tests,
  chHash.CRC.CRC3.Tests,
  chHash.CRC.CRC4.Tests,
  chHash.CRC.CRC5.Tests,
  chHash.CRC.CRC6.Tests,
  chHash.CRC.CRC7.Tests,
  chHash.CRC.CRC8.Tests,
  chHash.CRC.CRC10.Tests,
  chHash.CRC.CRC11.Tests,
  chHash.CRC.CRC12.Tests,
  chHash.CRC.CRC13.Tests,
  chHash.CRC.CRC14.Tests,
  chHash.CRC.CRC15.Tests,
  chHash.CRC.CRC16.Tests,
  chHash.CRC.CRC17.Tests,
  chHash.CRC.CRC31.Tests,
  chHash.CRC.CRC32.Tests,
  chHash.CRC.CRC21.Tests;

{$R *.RES}

begin
  ReportMemoryLeaksOnShutdown := True;
  DUnitTestRunner.RunRegisteredTests;
{$IFDEF CONSOLE_TESTRUNNER}
  Write('Для завершения нажмите "ENTER"');
  Readln;
{$ENDIF ~ CONSOLE_TESTRUNNER}
end.
